name-template: 'Release ${{ version }}'
tag-template: 'v${{ version }}'
category-template: '### ${{ heading }}'
change-template: '- ${{ change }} (@${{ contributor }})'
no-changes-template: 'No significant changes.'

categories:
  - title: 'ğŸš€ New Features'
    labels:
      - 'Type: Enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'Type: Bug'
  - title: 'ğŸ›  Maintenance'
    labels:
      - 'Type: Maintenance'
  - title: 'ğŸ“¦ Other Changes'
    labels:
      - '*'

exclude-labels:
  - 'skip-changelog'

template: |
  ## What's Changed
  ${{ CHANGELOG }}
